// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/image_command.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommandType represents the type of image processing command
type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED       CommandType = 0
	CommandType_COMMAND_TYPE_RESIZE            CommandType = 1
	CommandType_COMMAND_TYPE_FILTER            CommandType = 2
	CommandType_COMMAND_TYPE_TRANSFORM         CommandType = 3
	CommandType_COMMAND_TYPE_ANALYZE           CommandType = 4
	CommandType_COMMAND_TYPE_CROP              CommandType = 5
	CommandType_COMMAND_TYPE_REMOVE_BACKGROUND CommandType = 6
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_TYPE_RESIZE",
		2: "COMMAND_TYPE_FILTER",
		3: "COMMAND_TYPE_TRANSFORM",
		4: "COMMAND_TYPE_ANALYZE",
		5: "COMMAND_TYPE_CROP",
		6: "COMMAND_TYPE_REMOVE_BACKGROUND",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":       0,
		"COMMAND_TYPE_RESIZE":            1,
		"COMMAND_TYPE_FILTER":            2,
		"COMMAND_TYPE_TRANSFORM":         3,
		"COMMAND_TYPE_ANALYZE":           4,
		"COMMAND_TYPE_CROP":              5,
		"COMMAND_TYPE_REMOVE_BACKGROUND": 6,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_image_command_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_proto_image_command_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_image_command_proto_rawDescGZIP(), []int{0}
}

// ImageCommand represents a command to process an image
type ImageCommand struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Command  CommandType            `protobuf:"varint,2,opt,name=command,proto3,enum=image.v1.CommandType" json:"command,omitempty"`
	ImageUrl string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	// Parameters based on command type
	//
	// Types that are valid to be assigned to Parameters:
	//
	//	*ImageCommand_Resize
	//	*ImageCommand_Filter
	//	*ImageCommand_Transform
	//	*ImageCommand_Crop
	//	*ImageCommand_Analyze
	//	*ImageCommand_RemoveBackground
	Parameters    isImageCommand_Parameters `protobuf_oneof:"parameters"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageCommand) Reset() {
	*x = ImageCommand{}
	mi := &file_proto_image_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageCommand) ProtoMessage() {}

func (x *ImageCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageCommand.ProtoReflect.Descriptor instead.
func (*ImageCommand) Descriptor() ([]byte, []int) {
	return file_proto_image_command_proto_rawDescGZIP(), []int{0}
}

func (x *ImageCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageCommand) GetCommand() CommandType {
	if x != nil {
		return x.Command
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *ImageCommand) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ImageCommand) GetParameters() isImageCommand_Parameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ImageCommand) GetResize() *ResizeParameters {
	if x != nil {
		if x, ok := x.Parameters.(*ImageCommand_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *ImageCommand) GetFilter() *FilterParameters {
	if x != nil {
		if x, ok := x.Parameters.(*ImageCommand_Filter); ok {
			return x.Filter
		}
	}
	return nil
}

func (x *ImageCommand) GetTransform() *TransformParameters {
	if x != nil {
		if x, ok := x.Parameters.(*ImageCommand_Transform); ok {
			return x.Transform
		}
	}
	return nil
}

func (x *ImageCommand) GetCrop() *CropParameters {
	if x != nil {
		if x, ok := x.Parameters.(*ImageCommand_Crop); ok {
			return x.Crop
		}
	}
	return nil
}

func (x *ImageCommand) GetAnalyze() *AnalyzeParameters {
	if x != nil {
		if x, ok := x.Parameters.(*ImageCommand_Analyze); ok {
			return x.Analyze
		}
	}
	return nil
}

func (x *ImageCommand) GetRemoveBackground() *RemoveBackgroundParameters {
	if x != nil {
		if x, ok := x.Parameters.(*ImageCommand_RemoveBackground); ok {
			return x.RemoveBackground
		}
	}
	return nil
}

type isImageCommand_Parameters interface {
	isImageCommand_Parameters()
}

type ImageCommand_Resize struct {
	Resize *ResizeParameters `protobuf:"bytes,10,opt,name=resize,proto3,oneof"`
}

type ImageCommand_Filter struct {
	Filter *FilterParameters `protobuf:"bytes,11,opt,name=filter,proto3,oneof"`
}

type ImageCommand_Transform struct {
	Transform *TransformParameters `protobuf:"bytes,12,opt,name=transform,proto3,oneof"`
}

type ImageCommand_Crop struct {
	Crop *CropParameters `protobuf:"bytes,13,opt,name=crop,proto3,oneof"`
}

type ImageCommand_Analyze struct {
	Analyze *AnalyzeParameters `protobuf:"bytes,14,opt,name=analyze,proto3,oneof"`
}

type ImageCommand_RemoveBackground struct {
	RemoveBackground *RemoveBackgroundParameters `protobuf:"bytes,15,opt,name=remove_background,json=removeBackground,proto3,oneof"`
}

func (*ImageCommand_Resize) isImageCommand_Parameters() {}

func (*ImageCommand_Filter) isImageCommand_Parameters() {}

func (*ImageCommand_Transform) isImageCommand_Parameters() {}

func (*ImageCommand_Crop) isImageCommand_Parameters() {}

func (*ImageCommand_Analyze) isImageCommand_Parameters() {}

func (*ImageCommand_RemoveBackground) isImageCommand_Parameters() {}

// ResizeParameters for resize command
type ResizeParameters struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Width               int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height              int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	MaintainAspectRatio bool                   `protobuf:"varint,3,opt,name=maintain_aspect_ratio,json=maintainAspectRatio,proto3" json:"maintain_aspect_ratio,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResizeParameters) Reset() {
	*x = ResizeParameters{}
	mi := &file_proto_image_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeParameters) ProtoMessage() {}

func (x *ResizeParameters) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeParameters.ProtoReflect.Descriptor instead.
func (*ResizeParameters) Descriptor() ([]byte, []int) {
	return file_proto_image_command_proto_rawDescGZIP(), []int{1}
}

func (x *ResizeParameters) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ResizeParameters) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ResizeParameters) GetMaintainAspectRatio() bool {
	if x != nil {
		return x.MaintainAspectRatio
	}
	return false
}

// FilterParameters for filter command
type FilterParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterType    string                 `protobuf:"bytes,1,opt,name=filter_type,json=filterType,proto3" json:"filter_type,omitempty"` // blur, sharpen, grayscale, sepia, etc.
	Intensity     float64                `protobuf:"fixed64,2,opt,name=intensity,proto3" json:"intensity,omitempty"`                   // 0.0 to 1.0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterParameters) Reset() {
	*x = FilterParameters{}
	mi := &file_proto_image_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterParameters) ProtoMessage() {}

func (x *FilterParameters) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterParameters.ProtoReflect.Descriptor instead.
func (*FilterParameters) Descriptor() ([]byte, []int) {
	return file_proto_image_command_proto_rawDescGZIP(), []int{2}
}

func (x *FilterParameters) GetFilterType() string {
	if x != nil {
		return x.FilterType
	}
	return ""
}

func (x *FilterParameters) GetIntensity() float64 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

// TransformParameters for transform command
type TransformParameters struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RotationDegrees float64                `protobuf:"fixed64,1,opt,name=rotation_degrees,json=rotationDegrees,proto3" json:"rotation_degrees,omitempty"`
	FlipHorizontal  bool                   `protobuf:"varint,2,opt,name=flip_horizontal,json=flipHorizontal,proto3" json:"flip_horizontal,omitempty"`
	FlipVertical    bool                   `protobuf:"varint,3,opt,name=flip_vertical,json=flipVertical,proto3" json:"flip_vertical,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransformParameters) Reset() {
	*x = TransformParameters{}
	mi := &file_proto_image_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformParameters) ProtoMessage() {}

func (x *TransformParameters) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformParameters.ProtoReflect.Descriptor instead.
func (*TransformParameters) Descriptor() ([]byte, []int) {
	return file_proto_image_command_proto_rawDescGZIP(), []int{3}
}

func (x *TransformParameters) GetRotationDegrees() float64 {
	if x != nil {
		return x.RotationDegrees
	}
	return 0
}

func (x *TransformParameters) GetFlipHorizontal() bool {
	if x != nil {
		return x.FlipHorizontal
	}
	return false
}

func (x *TransformParameters) GetFlipVertical() bool {
	if x != nil {
		return x.FlipVertical
	}
	return false
}

// CropParameters for crop command
type CropParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CropParameters) Reset() {
	*x = CropParameters{}
	mi := &file_proto_image_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CropParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CropParameters) ProtoMessage() {}

func (x *CropParameters) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CropParameters.ProtoReflect.Descriptor instead.
func (*CropParameters) Descriptor() ([]byte, []int) {
	return file_proto_image_command_proto_rawDescGZIP(), []int{4}
}

func (x *CropParameters) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CropParameters) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *CropParameters) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CropParameters) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// AnalyzeParameters for AI analysis
type AnalyzeParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []string               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"` // model names to use for analysis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeParameters) Reset() {
	*x = AnalyzeParameters{}
	mi := &file_proto_image_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeParameters) ProtoMessage() {}

func (x *AnalyzeParameters) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeParameters.ProtoReflect.Descriptor instead.
func (*AnalyzeParameters) Descriptor() ([]byte, []int) {
	return file_proto_image_command_proto_rawDescGZIP(), []int{5}
}

func (x *AnalyzeParameters) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

// RemoveBackgroundParameters for AI background removal
type RemoveBackgroundParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputFormat  string                 `protobuf:"bytes,1,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"` // png, webp
	HighQuality   bool                   `protobuf:"varint,2,opt,name=high_quality,json=highQuality,proto3" json:"high_quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBackgroundParameters) Reset() {
	*x = RemoveBackgroundParameters{}
	mi := &file_proto_image_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBackgroundParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBackgroundParameters) ProtoMessage() {}

func (x *RemoveBackgroundParameters) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBackgroundParameters.ProtoReflect.Descriptor instead.
func (*RemoveBackgroundParameters) Descriptor() ([]byte, []int) {
	return file_proto_image_command_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveBackgroundParameters) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

func (x *RemoveBackgroundParameters) GetHighQuality() bool {
	if x != nil {
		return x.HighQuality
	}
	return false
}

// ProcessingResult represents the result of image processing
type ProcessingResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CommandId        string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success          bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	OutputUrl        string                 `protobuf:"bytes,3,opt,name=output_url,json=outputUrl,proto3" json:"output_url,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ProcessingTimeMs int64                  `protobuf:"varint,5,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessingResult) Reset() {
	*x = ProcessingResult{}
	mi := &file_proto_image_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingResult) ProtoMessage() {}

func (x *ProcessingResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingResult.ProtoReflect.Descriptor instead.
func (*ProcessingResult) Descriptor() ([]byte, []int) {
	return file_proto_image_command_proto_rawDescGZIP(), []int{7}
}

func (x *ProcessingResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ProcessingResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessingResult) GetOutputUrl() string {
	if x != nil {
		return x.OutputUrl
	}
	return ""
}

func (x *ProcessingResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ProcessingResult) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

var File_proto_image_command_proto protoreflect.FileDescriptor

const file_proto_image_command_proto_rawDesc = "" +
	"\n" +
	"\x19proto/image_command.proto\x12\bimage.v1\"\xe3\x03\n" +
	"\fImageCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\acommand\x18\x02 \x01(\x0e2\x15.image.v1.CommandTypeR\acommand\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x124\n" +
	"\x06resize\x18\n" +
	" \x01(\v2\x1a.image.v1.ResizeParametersH\x00R\x06resize\x124\n" +
	"\x06filter\x18\v \x01(\v2\x1a.image.v1.FilterParametersH\x00R\x06filter\x12=\n" +
	"\ttransform\x18\f \x01(\v2\x1d.image.v1.TransformParametersH\x00R\ttransform\x12.\n" +
	"\x04crop\x18\r \x01(\v2\x18.image.v1.CropParametersH\x00R\x04crop\x127\n" +
	"\aanalyze\x18\x0e \x01(\v2\x1b.image.v1.AnalyzeParametersH\x00R\aanalyze\x12S\n" +
	"\x11remove_background\x18\x0f \x01(\v2$.image.v1.RemoveBackgroundParametersH\x00R\x10removeBackgroundB\f\n" +
	"\n" +
	"parameters\"t\n" +
	"\x10ResizeParameters\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x122\n" +
	"\x15maintain_aspect_ratio\x18\x03 \x01(\bR\x13maintainAspectRatio\"Q\n" +
	"\x10FilterParameters\x12\x1f\n" +
	"\vfilter_type\x18\x01 \x01(\tR\n" +
	"filterType\x12\x1c\n" +
	"\tintensity\x18\x02 \x01(\x01R\tintensity\"\x8e\x01\n" +
	"\x13TransformParameters\x12)\n" +
	"\x10rotation_degrees\x18\x01 \x01(\x01R\x0frotationDegrees\x12'\n" +
	"\x0fflip_horizontal\x18\x02 \x01(\bR\x0eflipHorizontal\x12#\n" +
	"\rflip_vertical\x18\x03 \x01(\bR\fflipVertical\"Z\n" +
	"\x0eCropParameters\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"+\n" +
	"\x11AnalyzeParameters\x12\x16\n" +
	"\x06models\x18\x01 \x03(\tR\x06models\"d\n" +
	"\x1aRemoveBackgroundParameters\x12#\n" +
	"\routput_format\x18\x01 \x01(\tR\foutputFormat\x12!\n" +
	"\fhigh_quality\x18\x02 \x01(\bR\vhighQuality\"\xbd\x01\n" +
	"\x10ProcessingResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"output_url\x18\x03 \x01(\tR\toutputUrl\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12,\n" +
	"\x12processing_time_ms\x18\x05 \x01(\x03R\x10processingTimeMs*\xce\x01\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13COMMAND_TYPE_RESIZE\x10\x01\x12\x17\n" +
	"\x13COMMAND_TYPE_FILTER\x10\x02\x12\x1a\n" +
	"\x16COMMAND_TYPE_TRANSFORM\x10\x03\x12\x18\n" +
	"\x14COMMAND_TYPE_ANALYZE\x10\x04\x12\x15\n" +
	"\x11COMMAND_TYPE_CROP\x10\x05\x12\"\n" +
	"\x1eCOMMAND_TYPE_REMOVE_BACKGROUND\x10\x06B\x1fZ\x1dkafka-consumer/internal/pb;pbb\x06proto3"

var (
	file_proto_image_command_proto_rawDescOnce sync.Once
	file_proto_image_command_proto_rawDescData []byte
)

func file_proto_image_command_proto_rawDescGZIP() []byte {
	file_proto_image_command_proto_rawDescOnce.Do(func() {
		file_proto_image_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_image_command_proto_rawDesc), len(file_proto_image_command_proto_rawDesc)))
	})
	return file_proto_image_command_proto_rawDescData
}

var file_proto_image_command_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_image_command_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_image_command_proto_goTypes = []any{
	(CommandType)(0),                   // 0: image.v1.CommandType
	(*ImageCommand)(nil),               // 1: image.v1.ImageCommand
	(*ResizeParameters)(nil),           // 2: image.v1.ResizeParameters
	(*FilterParameters)(nil),           // 3: image.v1.FilterParameters
	(*TransformParameters)(nil),        // 4: image.v1.TransformParameters
	(*CropParameters)(nil),             // 5: image.v1.CropParameters
	(*AnalyzeParameters)(nil),          // 6: image.v1.AnalyzeParameters
	(*RemoveBackgroundParameters)(nil), // 7: image.v1.RemoveBackgroundParameters
	(*ProcessingResult)(nil),           // 8: image.v1.ProcessingResult
}
var file_proto_image_command_proto_depIdxs = []int32{
	0, // 0: image.v1.ImageCommand.command:type_name -> image.v1.CommandType
	2, // 1: image.v1.ImageCommand.resize:type_name -> image.v1.ResizeParameters
	3, // 2: image.v1.ImageCommand.filter:type_name -> image.v1.FilterParameters
	4, // 3: image.v1.ImageCommand.transform:type_name -> image.v1.TransformParameters
	5, // 4: image.v1.ImageCommand.crop:type_name -> image.v1.CropParameters
	6, // 5: image.v1.ImageCommand.analyze:type_name -> image.v1.AnalyzeParameters
	7, // 6: image.v1.ImageCommand.remove_background:type_name -> image.v1.RemoveBackgroundParameters
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_image_command_proto_init() }
func file_proto_image_command_proto_init() {
	if File_proto_image_command_proto != nil {
		return
	}
	file_proto_image_command_proto_msgTypes[0].OneofWrappers = []any{
		(*ImageCommand_Resize)(nil),
		(*ImageCommand_Filter)(nil),
		(*ImageCommand_Transform)(nil),
		(*ImageCommand_Crop)(nil),
		(*ImageCommand_Analyze)(nil),
		(*ImageCommand_RemoveBackground)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_image_command_proto_rawDesc), len(file_proto_image_command_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_image_command_proto_goTypes,
		DependencyIndexes: file_proto_image_command_proto_depIdxs,
		EnumInfos:         file_proto_image_command_proto_enumTypes,
		MessageInfos:      file_proto_image_command_proto_msgTypes,
	}.Build()
	File_proto_image_command_proto = out.File
	file_proto_image_command_proto_goTypes = nil
	file_proto_image_command_proto_depIdxs = nil
}
